apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-db-claim
  namespace: {{ .Values.namespace }}
spec:
  storageClassName: nfs-client
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi