apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hello-mongoexpress-app
  namespace: {{ .Values.namespace }}
spec:
  rules:
    - host: {{ .Values.ingress.mongo_express_hostname }}
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: mongodb-express-service
                port:
                  number: 8081