apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
type: Opaque
data:
  mongodb-root-username: {{ .Values.mongodb_root_username }}
  mongodb-root-password: {{ .Values.mongodb-root-password }}