apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
type: Opaque
data:
  mongodb-root-username: {{ .Values.secret.mongodb.root_username }}
  mongodb-root-password: {{ .Values.secret.mongodb.root-password }}