apiVersion: v1
kind: Service
metadata:
  name: mongodb-express-service
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: mongodb-express
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081